#!/bin/bash
set -e

lb config \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer live \
  --archive-areas "main contrib non-free-firmware" \
  --linux-flavours amd64 \
  --bootappend-live "boot=live components quiet"
